# Uncomment the next line to define a global platform for your project

# platform :ios, '13.7'

target 'MetroBookingSystem' do
  use_frameworks!
  
	pod 'MDatePickerView'
  pod 'DTGradientButton'
  
end
